name: Deploy

# action se bo izvedel ko pushamo ali pa mergamo na production vejo
on:
  push:
    branches:
      - q
  pull_request:
    branches:
      - q
      
jobs:
  # action se bo izvedel na ubuntu serverju 
  deploy:
    runs-on: ubuntu-latest

    steps:
      # github kopira nas repository v njihovo izvajalno okolje
    - name: Checkout code
      uses: actions/checkout@v2  

    - name: Send webhook
      uses: distributhor/workflow-webhook@v1
      with:
        webhook_url: http://20.56.20.111:5000/webhook
        data: '{"message": "New Docker image deployed"}'
